### ISSUE TITLE
Add Dependabot for automated dependency updates

### ISSUE THREAD

**Issue by fbtravi** [trueartisans/mozart#10]
Description
I would like to propose adding [Dependabot](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically) to this repository to automate dependency updates. This would help keep dependencies up-to-date, improve security, and reduce maintenance overhead.

Proposal

- Add a .github/dependabot.yml configuration file to enable Dependabot for this project.
- Configure it to monitor the npm ecosystem for updates to package.json and package-lock.json.
- Set up a schedule for automated pull requests with dependency updates.

Here is a suggested configuration:

```yaml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Change if package.json is not in the root
    schedule:
      interval: "weekly" # Options: daily, weekly, monthly
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"
```
Benefits

- Keeps dependencies secure and up-to-date automatically.
- Reduces the risk of introducing vulnerabilities.
- Saves time on manual updates.
- Improves long-term maintainability.

Next Steps

- I can open a PR with the suggested configuration file.
- However, some configurations need to be enabled at the repository level by someone with admin access:
- Enable GitHub Actions (if not already enabled).
- Configure security alerts and Dependabot alerts in the repository settings.
- Ensure the necessary permissions are in place for Dependabot to open pull requests.
- Let me know if you agree with this proposal — happy to help with the initial setup!
